import os
import argparse
import torch
from tqdm import tqdm
from utils.embeddings import EmbeddingProvider

def main():
    parser = argparse.ArgumentParser(description="Embed justifications generated by neuroLLM.")
    
    # Matching neuroLLM arguments
    parser.add_argument("--species", type=str, required=True, help="Species (e.g., human, macaque)")
    parser.add_argument("--atlas-name", type=str, required=True, help="Atlas name (e.g., DesikanKilliany68)")
    parser.add_argument("--model-name", type=str, default="gpt-4", help="The LLM used for the justification")
    parser.add_argument("--provider", type=str, default="local", choices=["local", "openai"], help="Embedding provider")
    parser.add_argument("--output-dir", type=str, default="results/embeddings", help="Where to save the vectors")

    args = parser.parse_args()

    # 1. Define the path where neuroLLM saves justifications
    # Pattern: results/{species}/{atlas}/{model}/justifications/
    just_path = os.path.join("results", args.species, args.atlas_name, args.model_name, "justifications")

    if not os.path.exists(just_path):
        print(f"Error: Justification directory not found at {just_path}")
        return

    # 2. Initialize the Embedding Provider
    print(f"Initializing {args.provider} embedding provider...")
    provider = EmbeddingProvider(provider_type=args.provider)

    # 3. Process Files
    embedded_data = {}
    files = [f for f in os.listdir(just_path) if f.endswith(".txt")]

    print(f"Found {len(files)} justification files. Starting embeddings...")

    for filename in tqdm(files):
        file_path = os.path.join(just_path, filename)
        
        with open(file_path, 'r', encoding='utf-8') as f:
            text = f.read().strip()
            
            if text:
                # The .embed method usually expects a list
                vector = provider.embed([text])
                # Store by filename (region_trial)
                embedded_data[filename.replace(".txt", "")] = vector

    # 4. Save Results
    os.makedirs(args.output_dir, exist_ok=True)
    save_name = f"{args.species}_{args.atlas_name}_{args.model_name}_justification_vectors.pt"
    save_path = os.path.join(args.output_dir, save_name)
    
    torch.save(embedded_data, save_path)
    print(f"\nSuccess! Embeddings saved to: {save_path}")

if __name__ == "__main__":
    main()
